In [4]:
import numpy as np
import os
import pandas as pd

In [5]:
SOSD_DIR = "/spinning/pari/SOSD/data/"

WK = "wiki_ts_200M_uint64"
QFN_TMP1 = "{}_equality_lookups_1M"
QFN_TMP2 = "{}_equality_lookups_10M"

In [6]:
fn = os.path.join(SOSD_DIR, WK)
data = np.fromfile(fn, dtype=np.uint64)

In [7]:
qdata1 = np.fromfile(os.path.join(SOSD_DIR, QFN_TMP1.format(WK)), dtype=np.uint64)
#qdata2 = os.path.join(SOSD_DIR, QFN_TMP1.format(WK))

In [8]:
print(len(data), len(qdata1))

200000001 2000001


In [9]:
un = np.unique(data)

In [10]:
len(un)

90437012

In [11]:
len(qdata1)

2000001

In [12]:
qdata1

array([   1000000, 1114884650,   13131386, ...,  316075293, 1103883090,
          9004616], dtype=uint64)

In [13]:
data

array([ 200000000,  979672113,  979672371, ..., 1216240435, 1216240436,
       1216240436], dtype=uint64)

In [14]:
print(np.max(data), np.min(data))

1216240436 200000000


In [15]:
tmp = data[data == qdata1[150]]

In [16]:
tmp

array([], dtype=uint64)

In [17]:
len(qdata1)

2000001

In [18]:
# dataset = pd.DataFrame({'Column1': data[:, 0], 'Column2': data[:, 1]})
df = pd.DataFrame({"col": data})

In [19]:
df.head(5)

col
0  200000000
1  979672113
2  979672371
3  979676171
4  979676223

In [20]:
dfc = df.groupby("col").size().reset_index()

In [21]:
dfc[0].describe(percentiles=[0.9, 0.99, 0.999, 0.9999])

count     9.043701e+07
mean      2.211484e+00
std       3.124949e+00
min       1.000000e+00
50%       2.000000e+00
90%       4.000000e+00
99%       7.000000e+00
99.9%     9.000000e+00
99.99%    1.100000e+01
max       2.102600e+04
Name: 0, dtype: float64

In [82]:
dfc.sort_values(by=0, ascending=False)

col      0
102758    1014648675  21026
102756    1014648191  16164
75534955  1199376360    142
3787620   1085804410    139
75535154  1199376569    138
...              ...    ...
28569701  1144552768      1
28569706  1144552773      1
28569707  1144552774      1
28569708  1144552775      1
45218506  1164803505      1

[90437012 rows x 2 columns]

In [83]:
len(dfc)

90437012

In [85]:
dfc2 = dfc[dfc["col"].isin(qdata1)]

In [87]:
len(dfc2)

996982

In [88]:
len(qdata1)

2000001

In [89]:
data2 = data[data == qdata1]

array([ 200000000,  979672113,  979672371, ..., 1216240435, 1216240436,
       1216240436], dtype=uint64)

In [92]:
#data == qdata1

In [93]:
df3 = df[df["col"].isin(qdata1)]

In [94]:
len(df3)

2199975